// Generated by gencpp from file thesis_msgs/FingerJoints.msg
// DO NOT EDIT!


#ifndef THESIS_MSGS_MESSAGE_FINGERJOINTS_H
#define THESIS_MSGS_MESSAGE_FINGERJOINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace thesis_msgs
{
template <class ContainerAllocator>
struct FingerJoints_
{
  typedef FingerJoints_<ContainerAllocator> Type;

  FingerJoints_()
    : values()  {
    }
  FingerJoints_(const ContainerAllocator& _alloc)
    : values(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _values_type;
  _values_type values;





  typedef boost::shared_ptr< ::thesis_msgs::FingerJoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::thesis_msgs::FingerJoints_<ContainerAllocator> const> ConstPtr;

}; // struct FingerJoints_

typedef ::thesis_msgs::FingerJoints_<std::allocator<void> > FingerJoints;

typedef boost::shared_ptr< ::thesis_msgs::FingerJoints > FingerJointsPtr;
typedef boost::shared_ptr< ::thesis_msgs::FingerJoints const> FingerJointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::thesis_msgs::FingerJoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::thesis_msgs::FingerJoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::thesis_msgs::FingerJoints_<ContainerAllocator1> & lhs, const ::thesis_msgs::FingerJoints_<ContainerAllocator2> & rhs)
{
  return lhs.values == rhs.values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::thesis_msgs::FingerJoints_<ContainerAllocator1> & lhs, const ::thesis_msgs::FingerJoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace thesis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::thesis_msgs::FingerJoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::thesis_msgs::FingerJoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::thesis_msgs::FingerJoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::thesis_msgs::FingerJoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thesis_msgs::FingerJoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thesis_msgs::FingerJoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::thesis_msgs::FingerJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9163d7c678dcd669317e43e46b63d96";
  }

  static const char* value(const ::thesis_msgs::FingerJoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9163d7c678dcd66ULL;
  static const uint64_t static_value2 = 0x9317e43e46b63d96ULL;
};

template<class ContainerAllocator>
struct DataType< ::thesis_msgs::FingerJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "thesis_msgs/FingerJoints";
  }

  static const char* value(const ::thesis_msgs::FingerJoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::thesis_msgs::FingerJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] values\n"
;
  }

  static const char* value(const ::thesis_msgs::FingerJoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::thesis_msgs::FingerJoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FingerJoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::thesis_msgs::FingerJoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::thesis_msgs::FingerJoints_<ContainerAllocator>& v)
  {
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // THESIS_MSGS_MESSAGE_FINGERJOINTS_H
