// Generated by gencpp from file thesis_msgs/LinearVelocity.msg
// DO NOT EDIT!


#ifndef THESIS_MSGS_MESSAGE_LINEARVELOCITY_H
#define THESIS_MSGS_MESSAGE_LINEARVELOCITY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace thesis_msgs
{
template <class ContainerAllocator>
struct LinearVelocity_
{
  typedef LinearVelocity_<ContainerAllocator> Type;

  LinearVelocity_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  LinearVelocity_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::thesis_msgs::LinearVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::thesis_msgs::LinearVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct LinearVelocity_

typedef ::thesis_msgs::LinearVelocity_<std::allocator<void> > LinearVelocity;

typedef boost::shared_ptr< ::thesis_msgs::LinearVelocity > LinearVelocityPtr;
typedef boost::shared_ptr< ::thesis_msgs::LinearVelocity const> LinearVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::thesis_msgs::LinearVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::thesis_msgs::LinearVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::thesis_msgs::LinearVelocity_<ContainerAllocator1> & lhs, const ::thesis_msgs::LinearVelocity_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::thesis_msgs::LinearVelocity_<ContainerAllocator1> & lhs, const ::thesis_msgs::LinearVelocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace thesis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::thesis_msgs::LinearVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::thesis_msgs::LinearVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::thesis_msgs::LinearVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::thesis_msgs::LinearVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thesis_msgs::LinearVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thesis_msgs::LinearVelocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::thesis_msgs::LinearVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::thesis_msgs::LinearVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::thesis_msgs::LinearVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "thesis_msgs/LinearVelocity";
  }

  static const char* value(const ::thesis_msgs::LinearVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::thesis_msgs::LinearVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::thesis_msgs::LinearVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::thesis_msgs::LinearVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinearVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::thesis_msgs::LinearVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::thesis_msgs::LinearVelocity_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THESIS_MSGS_MESSAGE_LINEARVELOCITY_H
