// Generated by gencpp from file thesis_msgs/Orientation.msg
// DO NOT EDIT!


#ifndef THESIS_MSGS_MESSAGE_ORIENTATION_H
#define THESIS_MSGS_MESSAGE_ORIENTATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace thesis_msgs
{
template <class ContainerAllocator>
struct Orientation_
{
  typedef Orientation_<ContainerAllocator> Type;

  Orientation_()
    : w(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  Orientation_(const ContainerAllocator& _alloc)
    : w(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _w_type;
  _w_type w;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::thesis_msgs::Orientation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::thesis_msgs::Orientation_<ContainerAllocator> const> ConstPtr;

}; // struct Orientation_

typedef ::thesis_msgs::Orientation_<std::allocator<void> > Orientation;

typedef boost::shared_ptr< ::thesis_msgs::Orientation > OrientationPtr;
typedef boost::shared_ptr< ::thesis_msgs::Orientation const> OrientationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::thesis_msgs::Orientation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::thesis_msgs::Orientation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::thesis_msgs::Orientation_<ContainerAllocator1> & lhs, const ::thesis_msgs::Orientation_<ContainerAllocator2> & rhs)
{
  return lhs.w == rhs.w &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::thesis_msgs::Orientation_<ContainerAllocator1> & lhs, const ::thesis_msgs::Orientation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace thesis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::thesis_msgs::Orientation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::thesis_msgs::Orientation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::thesis_msgs::Orientation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::thesis_msgs::Orientation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thesis_msgs::Orientation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thesis_msgs::Orientation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::thesis_msgs::Orientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b82aaf9e8e0ae143191a8612f5c5d4c";
  }

  static const char* value(const ::thesis_msgs::Orientation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b82aaf9e8e0ae14ULL;
  static const uint64_t static_value2 = 0x3191a8612f5c5d4cULL;
};

template<class ContainerAllocator>
struct DataType< ::thesis_msgs::Orientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "thesis_msgs/Orientation";
  }

  static const char* value(const ::thesis_msgs::Orientation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::thesis_msgs::Orientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 w\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::thesis_msgs::Orientation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::thesis_msgs::Orientation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.w);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Orientation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::thesis_msgs::Orientation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::thesis_msgs::Orientation_<ContainerAllocator>& v)
  {
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THESIS_MSGS_MESSAGE_ORIENTATION_H
