# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from thesis_msgs/DesiredWaypoint.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import thesis_msgs.msg

class DesiredWaypoint(genpy.Message):
  _md5sum = "a7144ae7a25595aa8a475a2f0b514fe7"
  _type = "thesis_msgs/DesiredWaypoint"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Position position
Orientation orientation
LinearVelocity linearVelocity
AngularVelocity angularVelocity
================================================================================
MSG: thesis_msgs/Position
float64 x
float64 y
float64 z
================================================================================
MSG: thesis_msgs/Orientation
float64 w
float64 x
float64 y
float64 z
================================================================================
MSG: thesis_msgs/LinearVelocity
float64 x
float64 y
float64 z
================================================================================
MSG: thesis_msgs/AngularVelocity
float64 x
float64 y
float64 z"""
  __slots__ = ['position','orientation','linearVelocity','angularVelocity']
  _slot_types = ['thesis_msgs/Position','thesis_msgs/Orientation','thesis_msgs/LinearVelocity','thesis_msgs/AngularVelocity']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       position,orientation,linearVelocity,angularVelocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DesiredWaypoint, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.position is None:
        self.position = thesis_msgs.msg.Position()
      if self.orientation is None:
        self.orientation = thesis_msgs.msg.Orientation()
      if self.linearVelocity is None:
        self.linearVelocity = thesis_msgs.msg.LinearVelocity()
      if self.angularVelocity is None:
        self.angularVelocity = thesis_msgs.msg.AngularVelocity()
    else:
      self.position = thesis_msgs.msg.Position()
      self.orientation = thesis_msgs.msg.Orientation()
      self.linearVelocity = thesis_msgs.msg.LinearVelocity()
      self.angularVelocity = thesis_msgs.msg.AngularVelocity()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_13d().pack(_x.position.x, _x.position.y, _x.position.z, _x.orientation.w, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.linearVelocity.x, _x.linearVelocity.y, _x.linearVelocity.z, _x.angularVelocity.x, _x.angularVelocity.y, _x.angularVelocity.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = thesis_msgs.msg.Position()
      if self.orientation is None:
        self.orientation = thesis_msgs.msg.Orientation()
      if self.linearVelocity is None:
        self.linearVelocity = thesis_msgs.msg.LinearVelocity()
      if self.angularVelocity is None:
        self.angularVelocity = thesis_msgs.msg.AngularVelocity()
      end = 0
      _x = self
      start = end
      end += 104
      (_x.position.x, _x.position.y, _x.position.z, _x.orientation.w, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.linearVelocity.x, _x.linearVelocity.y, _x.linearVelocity.z, _x.angularVelocity.x, _x.angularVelocity.y, _x.angularVelocity.z,) = _get_struct_13d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_13d().pack(_x.position.x, _x.position.y, _x.position.z, _x.orientation.w, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.linearVelocity.x, _x.linearVelocity.y, _x.linearVelocity.z, _x.angularVelocity.x, _x.angularVelocity.y, _x.angularVelocity.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = thesis_msgs.msg.Position()
      if self.orientation is None:
        self.orientation = thesis_msgs.msg.Orientation()
      if self.linearVelocity is None:
        self.linearVelocity = thesis_msgs.msg.LinearVelocity()
      if self.angularVelocity is None:
        self.angularVelocity = thesis_msgs.msg.AngularVelocity()
      end = 0
      _x = self
      start = end
      end += 104
      (_x.position.x, _x.position.y, _x.position.z, _x.orientation.w, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.linearVelocity.x, _x.linearVelocity.y, _x.linearVelocity.z, _x.angularVelocity.x, _x.angularVelocity.y, _x.angularVelocity.z,) = _get_struct_13d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_13d = None
def _get_struct_13d():
    global _struct_13d
    if _struct_13d is None:
        _struct_13d = struct.Struct("<13d")
    return _struct_13d
