# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from thesis_msgs/Error.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Error(genpy.Message):
  _md5sum = "cd3acb1596a75ae2de3d324b855e456f"
  _type = "thesis_msgs/Error"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 positionErrorX
float64 positionErrorY
float64 positionErrorZ
float64 orientationErrorX
float64 orientationErrorY
float64 orientationErrorZ"""
  __slots__ = ['positionErrorX','positionErrorY','positionErrorZ','orientationErrorX','orientationErrorY','orientationErrorZ']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       positionErrorX,positionErrorY,positionErrorZ,orientationErrorX,orientationErrorY,orientationErrorZ

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Error, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.positionErrorX is None:
        self.positionErrorX = 0.
      if self.positionErrorY is None:
        self.positionErrorY = 0.
      if self.positionErrorZ is None:
        self.positionErrorZ = 0.
      if self.orientationErrorX is None:
        self.orientationErrorX = 0.
      if self.orientationErrorY is None:
        self.orientationErrorY = 0.
      if self.orientationErrorZ is None:
        self.orientationErrorZ = 0.
    else:
      self.positionErrorX = 0.
      self.positionErrorY = 0.
      self.positionErrorZ = 0.
      self.orientationErrorX = 0.
      self.orientationErrorY = 0.
      self.orientationErrorZ = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.positionErrorX, _x.positionErrorY, _x.positionErrorZ, _x.orientationErrorX, _x.orientationErrorY, _x.orientationErrorZ))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.positionErrorX, _x.positionErrorY, _x.positionErrorZ, _x.orientationErrorX, _x.orientationErrorY, _x.orientationErrorZ,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.positionErrorX, _x.positionErrorY, _x.positionErrorZ, _x.orientationErrorX, _x.orientationErrorY, _x.orientationErrorZ))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.positionErrorX, _x.positionErrorY, _x.positionErrorZ, _x.orientationErrorX, _x.orientationErrorY, _x.orientationErrorZ,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
