; Auto-generated. Do not edit!


(cl:in-package motor_imagery-msg)


;//! \htmlinclude GrabGoal.msg.html

(cl:defclass <GrabGoal> (roslisp-msg-protocol:ros-message)
  ((object_position
    :reader object_position
    :initarg :object_position
    :type (cl:vector cl:float)
   :initform (cl:make-array 3 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass GrabGoal (<GrabGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GrabGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GrabGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name motor_imagery-msg:<GrabGoal> is deprecated: use motor_imagery-msg:GrabGoal instead.")))

(cl:ensure-generic-function 'object_position-val :lambda-list '(m))
(cl:defmethod object_position-val ((m <GrabGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader motor_imagery-msg:object_position-val is deprecated.  Use motor_imagery-msg:object_position instead.")
  (object_position m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GrabGoal>) ostream)
  "Serializes a message object of type '<GrabGoal>"
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'object_position))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GrabGoal>) istream)
  "Deserializes a message object of type '<GrabGoal>"
  (cl:setf (cl:slot-value msg 'object_position) (cl:make-array 3))
  (cl:let ((vals (cl:slot-value msg 'object_position)))
    (cl:dotimes (i 3)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GrabGoal>)))
  "Returns string type for a message object of type '<GrabGoal>"
  "motor_imagery/GrabGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GrabGoal)))
  "Returns string type for a message object of type 'GrabGoal"
  "motor_imagery/GrabGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GrabGoal>)))
  "Returns md5sum for a message object of type '<GrabGoal>"
  "c07a06593d6c3d51b7c871f52fd66a61")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GrabGoal)))
  "Returns md5sum for a message object of type 'GrabGoal"
  "c07a06593d6c3d51b7c871f52fd66a61")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GrabGoal>)))
  "Returns full string definition for message of type '<GrabGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# GOAL~%float64[3] object_position~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GrabGoal)))
  "Returns full string definition for message of type 'GrabGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# GOAL~%float64[3] object_position~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GrabGoal>))
  (cl:+ 0
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'object_position) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GrabGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GrabGoal
    (cl:cons ':object_position (object_position msg))
))
