; Auto-generated. Do not edit!


(cl:in-package motor_imagery-msg)


;//! \htmlinclude ReleaseGoal.msg.html

(cl:defclass <ReleaseGoal> (roslisp-msg-protocol:ros-message)
  ((release_position
    :reader release_position
    :initarg :release_position
    :type (cl:vector cl:float)
   :initform (cl:make-array 3 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass ReleaseGoal (<ReleaseGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ReleaseGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ReleaseGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name motor_imagery-msg:<ReleaseGoal> is deprecated: use motor_imagery-msg:ReleaseGoal instead.")))

(cl:ensure-generic-function 'release_position-val :lambda-list '(m))
(cl:defmethod release_position-val ((m <ReleaseGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader motor_imagery-msg:release_position-val is deprecated.  Use motor_imagery-msg:release_position instead.")
  (release_position m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ReleaseGoal>) ostream)
  "Serializes a message object of type '<ReleaseGoal>"
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'release_position))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ReleaseGoal>) istream)
  "Deserializes a message object of type '<ReleaseGoal>"
  (cl:setf (cl:slot-value msg 'release_position) (cl:make-array 3))
  (cl:let ((vals (cl:slot-value msg 'release_position)))
    (cl:dotimes (i 3)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ReleaseGoal>)))
  "Returns string type for a message object of type '<ReleaseGoal>"
  "motor_imagery/ReleaseGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ReleaseGoal)))
  "Returns string type for a message object of type 'ReleaseGoal"
  "motor_imagery/ReleaseGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ReleaseGoal>)))
  "Returns md5sum for a message object of type '<ReleaseGoal>"
  "fb30b7fc1693ae8b594278c08451ff30")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ReleaseGoal)))
  "Returns md5sum for a message object of type 'ReleaseGoal"
  "fb30b7fc1693ae8b594278c08451ff30")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ReleaseGoal>)))
  "Returns full string definition for message of type '<ReleaseGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# GOAL~%float64[3] release_position~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ReleaseGoal)))
  "Returns full string definition for message of type 'ReleaseGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# GOAL~%float64[3] release_position~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ReleaseGoal>))
  (cl:+ 0
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'release_position) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ReleaseGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ReleaseGoal
    (cl:cons ':release_position (release_position msg))
))
