// Generated by gencpp from file motor_imagery/GrabAndReleaseGoal.msg
// DO NOT EDIT!


#ifndef MOTOR_IMAGERY_MESSAGE_GRABANDRELEASEGOAL_H
#define MOTOR_IMAGERY_MESSAGE_GRABANDRELEASEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_imagery
{
template <class ContainerAllocator>
struct GrabAndReleaseGoal_
{
  typedef GrabAndReleaseGoal_<ContainerAllocator> Type;

  GrabAndReleaseGoal_()
    : object_position()
    , release_position()  {
      object_position.assign(0.0);

      release_position.assign(0.0);
  }
  GrabAndReleaseGoal_(const ContainerAllocator& _alloc)
    : object_position()
    , release_position()  {
  (void)_alloc;
      object_position.assign(0.0);

      release_position.assign(0.0);
  }



   typedef boost::array<double, 3>  _object_position_type;
  _object_position_type object_position;

   typedef boost::array<double, 3>  _release_position_type;
  _release_position_type release_position;





  typedef boost::shared_ptr< ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator> const> ConstPtr;

}; // struct GrabAndReleaseGoal_

typedef ::motor_imagery::GrabAndReleaseGoal_<std::allocator<void> > GrabAndReleaseGoal;

typedef boost::shared_ptr< ::motor_imagery::GrabAndReleaseGoal > GrabAndReleaseGoalPtr;
typedef boost::shared_ptr< ::motor_imagery::GrabAndReleaseGoal const> GrabAndReleaseGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator1> & lhs, const ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator2> & rhs)
{
  return lhs.object_position == rhs.object_position &&
    lhs.release_position == rhs.release_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator1> & lhs, const ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor_imagery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df67bc06e81c56f0c9b1d234140979c8";
  }

  static const char* value(const ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf67bc06e81c56f0ULL;
  static const uint64_t static_value2 = 0xc9b1d234140979c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_imagery/GrabAndReleaseGoal";
  }

  static const char* value(const ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# GOAL\n"
"float64[3] object_position\n"
"float64[3] release_position\n"
;
  }

  static const char* value(const ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_position);
      stream.next(m.release_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GrabAndReleaseGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_imagery::GrabAndReleaseGoal_<ContainerAllocator>& v)
  {
    s << indent << "object_position[]" << std::endl;
    for (size_t i = 0; i < v.object_position.size(); ++i)
    {
      s << indent << "  object_position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.object_position[i]);
    }
    s << indent << "release_position[]" << std::endl;
    for (size_t i = 0; i < v.release_position.size(); ++i)
    {
      s << indent << "  release_position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.release_position[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_IMAGERY_MESSAGE_GRABANDRELEASEGOAL_H
