// Generated by gencpp from file motor_imagery/GrabGoal.msg
// DO NOT EDIT!


#ifndef MOTOR_IMAGERY_MESSAGE_GRABGOAL_H
#define MOTOR_IMAGERY_MESSAGE_GRABGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_imagery
{
template <class ContainerAllocator>
struct GrabGoal_
{
  typedef GrabGoal_<ContainerAllocator> Type;

  GrabGoal_()
    : object_position()  {
      object_position.assign(0.0);
  }
  GrabGoal_(const ContainerAllocator& _alloc)
    : object_position()  {
  (void)_alloc;
      object_position.assign(0.0);
  }



   typedef boost::array<double, 3>  _object_position_type;
  _object_position_type object_position;





  typedef boost::shared_ptr< ::motor_imagery::GrabGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_imagery::GrabGoal_<ContainerAllocator> const> ConstPtr;

}; // struct GrabGoal_

typedef ::motor_imagery::GrabGoal_<std::allocator<void> > GrabGoal;

typedef boost::shared_ptr< ::motor_imagery::GrabGoal > GrabGoalPtr;
typedef boost::shared_ptr< ::motor_imagery::GrabGoal const> GrabGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_imagery::GrabGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_imagery::GrabGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor_imagery::GrabGoal_<ContainerAllocator1> & lhs, const ::motor_imagery::GrabGoal_<ContainerAllocator2> & rhs)
{
  return lhs.object_position == rhs.object_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor_imagery::GrabGoal_<ContainerAllocator1> & lhs, const ::motor_imagery::GrabGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor_imagery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motor_imagery::GrabGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_imagery::GrabGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_imagery::GrabGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_imagery::GrabGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_imagery::GrabGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_imagery::GrabGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_imagery::GrabGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c07a06593d6c3d51b7c871f52fd66a61";
  }

  static const char* value(const ::motor_imagery::GrabGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc07a06593d6c3d51ULL;
  static const uint64_t static_value2 = 0xb7c871f52fd66a61ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_imagery::GrabGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_imagery/GrabGoal";
  }

  static const char* value(const ::motor_imagery::GrabGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_imagery::GrabGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# GOAL\n"
"float64[3] object_position\n"
;
  }

  static const char* value(const ::motor_imagery::GrabGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_imagery::GrabGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GrabGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_imagery::GrabGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_imagery::GrabGoal_<ContainerAllocator>& v)
  {
    s << indent << "object_position[]" << std::endl;
    for (size_t i = 0; i < v.object_position.size(); ++i)
    {
      s << indent << "  object_position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.object_position[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_IMAGERY_MESSAGE_GRABGOAL_H
