// Generated by gencpp from file motor_imagery/MoveFeedback.msg
// DO NOT EDIT!


#ifndef MOTOR_IMAGERY_MESSAGE_MOVEFEEDBACK_H
#define MOTOR_IMAGERY_MESSAGE_MOVEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_imagery
{
template <class ContainerAllocator>
struct MoveFeedback_
{
  typedef MoveFeedback_<ContainerAllocator> Type;

  MoveFeedback_()
    : percentage(0.0)  {
    }
  MoveFeedback_(const ContainerAllocator& _alloc)
    : percentage(0.0)  {
  (void)_alloc;
    }



   typedef double _percentage_type;
  _percentage_type percentage;





  typedef boost::shared_ptr< ::motor_imagery::MoveFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_imagery::MoveFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MoveFeedback_

typedef ::motor_imagery::MoveFeedback_<std::allocator<void> > MoveFeedback;

typedef boost::shared_ptr< ::motor_imagery::MoveFeedback > MoveFeedbackPtr;
typedef boost::shared_ptr< ::motor_imagery::MoveFeedback const> MoveFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_imagery::MoveFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_imagery::MoveFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor_imagery::MoveFeedback_<ContainerAllocator1> & lhs, const ::motor_imagery::MoveFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percentage == rhs.percentage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor_imagery::MoveFeedback_<ContainerAllocator1> & lhs, const ::motor_imagery::MoveFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor_imagery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motor_imagery::MoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_imagery::MoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_imagery::MoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_imagery::MoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_imagery::MoveFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_imagery::MoveFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_imagery::MoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46302a97c06fe5a4416c427fe6ee8804";
  }

  static const char* value(const ::motor_imagery::MoveFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46302a97c06fe5a4ULL;
  static const uint64_t static_value2 = 0x416c427fe6ee8804ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_imagery::MoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_imagery/MoveFeedback";
  }

  static const char* value(const ::motor_imagery::MoveFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_imagery::MoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# FEEDBACK\n"
"float64 percentage\n"
;
  }

  static const char* value(const ::motor_imagery::MoveFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_imagery::MoveFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_imagery::MoveFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_imagery::MoveFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percentage: ";
    Printer<double>::stream(s, indent + "  ", v.percentage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_IMAGERY_MESSAGE_MOVEFEEDBACK_H
