// Generated by gencpp from file motor_imagery/ReleaseFeedback.msg
// DO NOT EDIT!


#ifndef MOTOR_IMAGERY_MESSAGE_RELEASEFEEDBACK_H
#define MOTOR_IMAGERY_MESSAGE_RELEASEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_imagery
{
template <class ContainerAllocator>
struct ReleaseFeedback_
{
  typedef ReleaseFeedback_<ContainerAllocator> Type;

  ReleaseFeedback_()
    : phase()  {
    }
  ReleaseFeedback_(const ContainerAllocator& _alloc)
    : phase(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _phase_type;
  _phase_type phase;





  typedef boost::shared_ptr< ::motor_imagery::ReleaseFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_imagery::ReleaseFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ReleaseFeedback_

typedef ::motor_imagery::ReleaseFeedback_<std::allocator<void> > ReleaseFeedback;

typedef boost::shared_ptr< ::motor_imagery::ReleaseFeedback > ReleaseFeedbackPtr;
typedef boost::shared_ptr< ::motor_imagery::ReleaseFeedback const> ReleaseFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_imagery::ReleaseFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_imagery::ReleaseFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor_imagery::ReleaseFeedback_<ContainerAllocator1> & lhs, const ::motor_imagery::ReleaseFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.phase == rhs.phase;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor_imagery::ReleaseFeedback_<ContainerAllocator1> & lhs, const ::motor_imagery::ReleaseFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor_imagery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motor_imagery::ReleaseFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_imagery::ReleaseFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_imagery::ReleaseFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_imagery::ReleaseFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_imagery::ReleaseFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_imagery::ReleaseFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_imagery::ReleaseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d2d7be4891f7e41e801034b05c9586c";
  }

  static const char* value(const ::motor_imagery::ReleaseFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d2d7be4891f7e41ULL;
  static const uint64_t static_value2 = 0xe801034b05c9586cULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_imagery::ReleaseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_imagery/ReleaseFeedback";
  }

  static const char* value(const ::motor_imagery::ReleaseFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_imagery::ReleaseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# FEEDBACK\n"
"string phase\n"
;
  }

  static const char* value(const ::motor_imagery::ReleaseFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_imagery::ReleaseFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.phase);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReleaseFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_imagery::ReleaseFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_imagery::ReleaseFeedback_<ContainerAllocator>& v)
  {
    s << indent << "phase: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.phase);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_IMAGERY_MESSAGE_RELEASEFEEDBACK_H
