// Generated by gencpp from file motor_imagery/sendInitPoseRequest.msg
// DO NOT EDIT!


#ifndef MOTOR_IMAGERY_MESSAGE_SENDINITPOSEREQUEST_H
#define MOTOR_IMAGERY_MESSAGE_SENDINITPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_imagery
{
template <class ContainerAllocator>
struct sendInitPoseRequest_
{
  typedef sendInitPoseRequest_<ContainerAllocator> Type;

  sendInitPoseRequest_()
    {
    }
  sendInitPoseRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::motor_imagery::sendInitPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_imagery::sendInitPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct sendInitPoseRequest_

typedef ::motor_imagery::sendInitPoseRequest_<std::allocator<void> > sendInitPoseRequest;

typedef boost::shared_ptr< ::motor_imagery::sendInitPoseRequest > sendInitPoseRequestPtr;
typedef boost::shared_ptr< ::motor_imagery::sendInitPoseRequest const> sendInitPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_imagery::sendInitPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_imagery::sendInitPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace motor_imagery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motor_imagery::sendInitPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_imagery::sendInitPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_imagery::sendInitPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_imagery::sendInitPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_imagery::sendInitPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_imagery::sendInitPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_imagery::sendInitPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::motor_imagery::sendInitPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_imagery::sendInitPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_imagery/sendInitPoseRequest";
  }

  static const char* value(const ::motor_imagery::sendInitPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_imagery::sendInitPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::motor_imagery::sendInitPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_imagery::sendInitPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sendInitPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_imagery::sendInitPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::motor_imagery::sendInitPoseRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_IMAGERY_MESSAGE_SENDINITPOSEREQUEST_H
