// Generated by gencpp from file motor_imagery/sendInitPose.msg
// DO NOT EDIT!


#ifndef MOTOR_IMAGERY_MESSAGE_SENDINITPOSE_H
#define MOTOR_IMAGERY_MESSAGE_SENDINITPOSE_H

#include <ros/service_traits.h>


#include <motor_imagery/sendInitPoseRequest.h>
#include <motor_imagery/sendInitPoseResponse.h>


namespace motor_imagery
{

struct sendInitPose
{

typedef sendInitPoseRequest Request;
typedef sendInitPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sendInitPose
} // namespace motor_imagery


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motor_imagery::sendInitPose > {
  static const char* value()
  {
    return "aacdf94e500adc5f450c7a9051b9b0a3";
  }

  static const char* value(const ::motor_imagery::sendInitPose&) { return value(); }
};

template<>
struct DataType< ::motor_imagery::sendInitPose > {
  static const char* value()
  {
    return "motor_imagery/sendInitPose";
  }

  static const char* value(const ::motor_imagery::sendInitPose&) { return value(); }
};


// service_traits::MD5Sum< ::motor_imagery::sendInitPoseRequest> should match
// service_traits::MD5Sum< ::motor_imagery::sendInitPose >
template<>
struct MD5Sum< ::motor_imagery::sendInitPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motor_imagery::sendInitPose >::value();
  }
  static const char* value(const ::motor_imagery::sendInitPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor_imagery::sendInitPoseRequest> should match
// service_traits::DataType< ::motor_imagery::sendInitPose >
template<>
struct DataType< ::motor_imagery::sendInitPoseRequest>
{
  static const char* value()
  {
    return DataType< ::motor_imagery::sendInitPose >::value();
  }
  static const char* value(const ::motor_imagery::sendInitPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motor_imagery::sendInitPoseResponse> should match
// service_traits::MD5Sum< ::motor_imagery::sendInitPose >
template<>
struct MD5Sum< ::motor_imagery::sendInitPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motor_imagery::sendInitPose >::value();
  }
  static const char* value(const ::motor_imagery::sendInitPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor_imagery::sendInitPoseResponse> should match
// service_traits::DataType< ::motor_imagery::sendInitPose >
template<>
struct DataType< ::motor_imagery::sendInitPoseResponse>
{
  static const char* value()
  {
    return DataType< ::motor_imagery::sendInitPose >::value();
  }
  static const char* value(const ::motor_imagery::sendInitPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTOR_IMAGERY_MESSAGE_SENDINITPOSE_H
