// Generated by gencpp from file motor_imagery/sendInitState.msg
// DO NOT EDIT!


#ifndef MOTOR_IMAGERY_MESSAGE_SENDINITSTATE_H
#define MOTOR_IMAGERY_MESSAGE_SENDINITSTATE_H

#include <ros/service_traits.h>


#include <motor_imagery/sendInitStateRequest.h>
#include <motor_imagery/sendInitStateResponse.h>


namespace motor_imagery
{

struct sendInitState
{

typedef sendInitStateRequest Request;
typedef sendInitStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sendInitState
} // namespace motor_imagery


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motor_imagery::sendInitState > {
  static const char* value()
  {
    return "f72ac98c261a7db30a72292fcddffa92";
  }

  static const char* value(const ::motor_imagery::sendInitState&) { return value(); }
};

template<>
struct DataType< ::motor_imagery::sendInitState > {
  static const char* value()
  {
    return "motor_imagery/sendInitState";
  }

  static const char* value(const ::motor_imagery::sendInitState&) { return value(); }
};


// service_traits::MD5Sum< ::motor_imagery::sendInitStateRequest> should match
// service_traits::MD5Sum< ::motor_imagery::sendInitState >
template<>
struct MD5Sum< ::motor_imagery::sendInitStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motor_imagery::sendInitState >::value();
  }
  static const char* value(const ::motor_imagery::sendInitStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor_imagery::sendInitStateRequest> should match
// service_traits::DataType< ::motor_imagery::sendInitState >
template<>
struct DataType< ::motor_imagery::sendInitStateRequest>
{
  static const char* value()
  {
    return DataType< ::motor_imagery::sendInitState >::value();
  }
  static const char* value(const ::motor_imagery::sendInitStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motor_imagery::sendInitStateResponse> should match
// service_traits::MD5Sum< ::motor_imagery::sendInitState >
template<>
struct MD5Sum< ::motor_imagery::sendInitStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motor_imagery::sendInitState >::value();
  }
  static const char* value(const ::motor_imagery::sendInitStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor_imagery::sendInitStateResponse> should match
// service_traits::DataType< ::motor_imagery::sendInitState >
template<>
struct DataType< ::motor_imagery::sendInitStateResponse>
{
  static const char* value()
  {
    return DataType< ::motor_imagery::sendInitState >::value();
  }
  static const char* value(const ::motor_imagery::sendInitStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTOR_IMAGERY_MESSAGE_SENDINITSTATE_H
