// Generated by gencpp from file motor_imagery/sendInitPoseResponse.msg
// DO NOT EDIT!


#ifndef MOTOR_IMAGERY_MESSAGE_SENDINITPOSERESPONSE_H
#define MOTOR_IMAGERY_MESSAGE_SENDINITPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_imagery
{
template <class ContainerAllocator>
struct sendInitPoseResponse_
{
  typedef sendInitPoseResponse_<ContainerAllocator> Type;

  sendInitPoseResponse_()
    : position()
    , orientation()  {
    }
  sendInitPoseResponse_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , orientation(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _position_type;
  _position_type position;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _orientation_type;
  _orientation_type orientation;





  typedef boost::shared_ptr< ::motor_imagery::sendInitPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_imagery::sendInitPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct sendInitPoseResponse_

typedef ::motor_imagery::sendInitPoseResponse_<std::allocator<void> > sendInitPoseResponse;

typedef boost::shared_ptr< ::motor_imagery::sendInitPoseResponse > sendInitPoseResponsePtr;
typedef boost::shared_ptr< ::motor_imagery::sendInitPoseResponse const> sendInitPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_imagery::sendInitPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_imagery::sendInitPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor_imagery::sendInitPoseResponse_<ContainerAllocator1> & lhs, const ::motor_imagery::sendInitPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.orientation == rhs.orientation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor_imagery::sendInitPoseResponse_<ContainerAllocator1> & lhs, const ::motor_imagery::sendInitPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor_imagery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motor_imagery::sendInitPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_imagery::sendInitPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_imagery::sendInitPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_imagery::sendInitPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_imagery::sendInitPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_imagery::sendInitPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_imagery::sendInitPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aacdf94e500adc5f450c7a9051b9b0a3";
  }

  static const char* value(const ::motor_imagery::sendInitPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaacdf94e500adc5fULL;
  static const uint64_t static_value2 = 0x450c7a9051b9b0a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_imagery::sendInitPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_imagery/sendInitPoseResponse";
  }

  static const char* value(const ::motor_imagery::sendInitPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_imagery::sendInitPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] position     # Vector (x, y, z)\n"
"float64[] orientation  # Quaternion (w, x, y, z)\n"
;
  }

  static const char* value(const ::motor_imagery::sendInitPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_imagery::sendInitPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sendInitPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_imagery::sendInitPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_imagery::sendInitPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "orientation[]" << std::endl;
    for (size_t i = 0; i < v.orientation.size(); ++i)
    {
      s << indent << "  orientation[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.orientation[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_IMAGERY_MESSAGE_SENDINITPOSERESPONSE_H
