(cl:defpackage motor_imagery-srv
  (:use )
  (:export
   "SENDINITPOSE"
   "<SENDINITPOSE-REQUEST>"
   "SENDINITPOSE-REQUEST"
   "<SENDINITPOSE-RESPONSE>"
   "SENDINITPOSE-RESPONSE"
   "SENDINITSTATE"
   "<SENDINITSTATE-REQUEST>"
   "SENDINITSTATE-REQUEST"
   "<SENDINITSTATE-RESPONSE>"
   "SENDINITSTATE-RESPONSE"
  ))

