(cl:in-package thesis_msgs-msg)
(cl:export '(POSITIONERRORX-VAL
          POSITIONERRORX
          POSITIONERRORY-VAL
          POSITIONERRORY
          POSITIONERRORZ-VAL
          POSITIONERRORZ
          ORIENTATIONERRORX-VAL
          ORIENTATIONERRORX
          ORIENTATIONERRORY-VAL
          ORIENTATIONERRORY
          ORIENTATIONERRORZ-VAL
          ORIENTATIONERRORZ
))