(cl:defpackage thesis_msgs-msg
  (:use )
  (:export
   "<ANGULARVELOCITY>"
   "ANGULARVELOCITY"
   "<DESIREDWAYPOINT>"
   "DESIREDWAYPOINT"
   "<ERROR>"
   "ERROR"
   "<FINGERJOINTS>"
   "FINGERJOINTS"
   "<LINEARVELOCITY>"
   "LINEARVELOCITY"
   "<ORIENTATION>"
   "ORIENTATION"
   "<POSITION>"
   "POSITION"
  ))

